maxMineCount: 40
maxDistance: 11

# Shape excavation support.
enableShape: false

# Should mine diagonally(BFS). Otherwise will DFS.
diagonally: false

# Automatically collect drops into players' inventory.
autoPickup: true

# Damage tool.
damageTool: true
# Stop excavate before tool break.
dontBreakTool: true

# Prevent tool mismatch.
requireToolMatches: false
customToolsMatch:
  # Tool Material:
  #  - Block Material

# Group for excavating.
customGroup:
  # GroupName:
  #  - Block Material

blocklist: []

# Allowlist have a higher priority than blocklist.
enableAllowList: false
allowlist: []
