maxMineCount: 40
maxDistance: 11

# Should mine diagonally(DFS). Otherwise will BFS.
diagonallyMine: true

# Automatically collect drops into players' inventory.
autoPickup: true

# Damage tool.
damageTool: true
# Stop excavate before tool break.
dontBreakTool: true

# Shape excavation support.
enableShape: true

# Shape excavation ignore block type.
shapeIgnoresBlockMismatch: true

# Prevent tool mismatch.
requireToolMatches: false
customToolsMatch:
  # Tool Material:
  #  - Block Material

# Group for excavating.
customGroup:
  # GroupName:
  #  - Block Material

blocklist: []

# Allowlist have a higher priority than blocklist.
enableAllowList: false
allowlist: []
